services:
  web:
    image: dr-x/web:latest
    build:
      context: ../web
      dockerfile: ../web/Dockerfile
    container_name: web
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

networks:
  app-network:
    driver: bridge
